# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alfredo Torre
author: sentenza
email: alfredotorre@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The coding weblog of Alfredo Torre (aka sentenza)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://torre.me.uk" # the base hostname & protocol for your site, e.g. http://example.com
lang: en-GB
twitter_username: 
github_username:  sentenza
google_analytics: UA-3444253-11
remote_theme: yous/whiteglass

# Build settings
markdown: kramdown
# theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5
comments: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
